### PR TITLE
Revamp of the amp_heatmap() function to display samplewise top tax levels

### PR DESCRIPTION
**Pull request by brendbech**
In my own work i've used your package to display heatmaps of phyloseq objects, but unfortunately the way the amp_heatmap() function displays the top n OTUs was not adequate for my employer.

The problem with the amp_heatmap() function is that it shows which taxa are most prevalent (abundant) across all samples, which can result in some taxa not being displayed as top abundant. 
image
In the example above, we can see that some samples have only few highly abundant genera displayed as OTUs from other samples "overshadow" their abundance, thereby stating that "Leuconostoc" is the top genera for many samples that barely have it present. This is a problem when you want to screen for pathogens, and therefore I took inspiration from your heatmap, and made my own revamped version that shows the top n OTUs for each sample.

The result is this:
image

I do believe this gives a much clearer picture of what OTU is where. At this moment, the function is not as equipped as yours is, as it does only have ~5 inputs for choosing taxa, and number of top OTUs and so on, but if there is any interest from you to use this/publish this code, then I will try to make it as compatible/similar to your heatmap function as possible.

### CODE REVIEW

**Comment by brendbech** [comment]
Sorry about this. I totally misunderstood how pull requests work. Is it possible for me to delete this again? I just wanted to give you the file with the amp_heatmap_samplewise() function code.

**Comment by KasperSkytte** [comment]
Hi there

I like the idea! It could be an option in `amp_heatmap` to plot it in this way. It does provide a different type of overview, though the main goal of the heatmap in our usecases is to provide an "overall" overview of the most abundant taxa across all samples. I do think that if the samples in the data set are so different and are to be analyzed separately, there is no point in having them grouped together in the same data set in the first place. 

But yes, pull requests are for suggesting changes to the existing code base, so you would fork the repo, experiment and test some changes, and then make a PR describing what it does and why. I'd like to see the code for inspiration, though I'm off for a long holiday now.

**Comment by brendbech** [comment]
Ok, sorry for the inconvenience. I agree about your statement about analyzing different samples separately, but here where I work, that is just not how they use it as they use the nanopore for exploration and screening of products. That means potentially  a lot of different OTU's with varying degrees of abundance for each sample.

Anyways, how can I give you the code then? Should I just paste it here in a comment?

Have a nice holiday.

**Comment by KasperSkytte** [comment]
If you have experience with developing R packages, then you just fork, make the changes, update documentation, write tests etc, and then make a pull request I can review. If not I'll take a look at the code and see how to implement it. It would be a nice addition to the function, I can see its uses. You can just post here, make a gist and link it, or fork, add the file, then make PR. Then you would also show as contributor to ampvis2 on github. Up to you, whatever works for me

**Pull request closed without merging**
